### ISSUE TITLE
fah-client package v8.1.5 doesn't run on older (2018) Linux

### ISSUE THREAD

**Issue by Hou5e** [FoldingAtHome/fah-client-bastet#66]
Trying to run fah-client from the command line on Linux Mint v19.0, give the following errors:
```
fah-client
fah-client: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by fah-client)
fah-client: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by fah-client)
```

```
Linux Mint v19.0 (or 19.3): ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
```

I'll upgrade this Folding box to a newer version of Linux, but that might not be an option for some people.
The download web page might need some warnings about minimum versions supported, and to run FAH v7 on older Linux.

---

Trying to build from source also has problems with prerequisite conflicts:

```
sudo apt-get install -y libssl-dev

The following packages will be REMOVED:
  libssl1.0-dev node-gyp nodejs-dev npm
The following NEW packages will be installed:
  libssl-dev
```

```
sudo apt-get install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libssl1.0-dev node-gyp nodejs-dev
Suggested packages:
  debhelper
The following packages will be REMOVED:
  libssl-dev
The following NEW packages will be installed:
  libssl1.0-dev node-gyp nodejs-dev npm
```
---

Trying to build anyway following the instructions on GitHub, has a bunch of errors, as expected, like:
Have you set PKG_HOME?
Have you set PACKAGER_HOME?
Exception: CBANG_HOME not set?

**Comment by kbernhagen** [comment]
Did you do these steps?
```
export CBANG_HOME=$PWD/cbang
scons -C cbang
scons -C fah-client-bastet
scons -C fah-client-bastet package
```

**Comment by Hou5e** [comment]
Yes. There are probably a fair number of things that aren't going to work without the correct perquisites.
It is running Python 2.7.17, too.
```
jeff@X99-15:~$ export CBANG_HOME=$PWD/cbang
jeff@X99-15:~$ scons -C cbang
scons: Entering directory `/home/jeff/cbang'
scons: Reading SConscript files ...
Traceback (most recent call last):
  File "/home/jeff/cbang/config/__init__.py", line 201, in CBTryLoadTool
    env.Tool(name, toolpath = [path])
  File "/usr/lib/scons/SCons/Environment.py", line 1788, in Tool
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 118, in __init__
    module = self._tool_module()
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 145, in _tool_module
    mod, file = self._load_dotted_module_py2(self.name, self.name, self.toolpath)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 130, in _load_dotted_module_py2
    mod = imp.load_module(full_name, file, path, desc)
  File "/home/jeff/cbang/config/pkg/__init__.py", line 13, in <module>
    xml_escape_table = str.maketrans({
AttributeError: type object 'str' has no attribute 'maketrans'
Traceback (most recent call last):
  File "/home/jeff/cbang/config/__init__.py", line 201, in CBTryLoadTool
    env.Tool(name, toolpath = [path])
  File "/usr/lib/scons/SCons/Environment.py", line 1788, in Tool
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 118, in __init__
    module = self._tool_module()
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 145, in _tool_module
    mod, file = self._load_dotted_module_py2(self.name, self.name, self.toolpath)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 130, in _load_dotted_module_py2
    mod = imp.load_module(full_name, file, path, desc)
  File "/home/jeff/cbang/config/pkg/__init__.py", line 13, in <module>
    xml_escape_table = str.maketrans({
AttributeError: type object 'str' has no attribute 'maketrans'
Traceback (most recent call last):
  File "/home/jeff/cbang/config/__init__.py", line 201, in CBTryLoadTool
    env.Tool(name, toolpath = [path])
  File "/usr/lib/scons/SCons/Environment.py", line 1788, in Tool
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 118, in __init__
    module = self._tool_module()
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 145, in _tool_module
    mod, file = self._load_dotted_module_py2(self.name, self.name, self.toolpath)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 130, in _load_dotted_module_py2
    mod = imp.load_module(full_name, file, path, desc)
  File "/home/jeff/cbang/config/pkg/__init__.py", line 13, in <module>
    xml_escape_table = str.maketrans({
AttributeError: type object 'str' has no attribute 'maketrans'
Failed to load tool pkg from the following paths:
  /home/jeff/cbang/config
  /home/jeff/cbang/config
  ./config
Have you set PKG_HOME?
Traceback (most recent call last):
  File "/home/jeff/cbang/config/__init__.py", line 201, in CBTryLoadTool
    env.Tool(name, toolpath = [path])
  File "/usr/lib/scons/SCons/Environment.py", line 1789, in Tool
    tool(self)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 298, in __call__
    self.generate(env, *args, **kw)
  File "/home/jeff/cbang/config/packager/__init__.py", line 315, in generate
    env.CBLoadTool(tool)
  File "/usr/lib/scons/SCons/Environment.py", line 224, in __call__
    return self.method(*nargs, **kwargs)
  File "/home/jeff/cbang/config/__init__.py", line 239, in CBLoadTool
    raise Exception('Failed to load tool ' + name)
Exception: Failed to load tool pkg
Traceback (most recent call last):
  File "/home/jeff/cbang/config/__init__.py", line 201, in CBTryLoadTool
    env.Tool(name, toolpath = [path])
  File "/usr/lib/scons/SCons/Environment.py", line 1788, in Tool
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 118, in __init__
    module = self._tool_module()
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 145, in _tool_module
    mod, file = self._load_dotted_module_py2(self.name, self.name, self.toolpath)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 130, in _load_dotted_module_py2
    mod = imp.load_module(full_name, file, path, desc)
  File "/home/jeff/cbang/config/pkg/__init__.py", line 13, in <module>
    xml_escape_table = str.maketrans({
AttributeError: type object 'str' has no attribute 'maketrans'
Traceback (most recent call last):
  File "/home/jeff/cbang/config/__init__.py", line 201, in CBTryLoadTool
    env.Tool(name, toolpath = [path])
  File "/usr/lib/scons/SCons/Environment.py", line 1788, in Tool
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 118, in __init__
    module = self._tool_module()
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 145, in _tool_module
    mod, file = self._load_dotted_module_py2(self.name, self.name, self.toolpath)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 130, in _load_dotted_module_py2
    mod = imp.load_module(full_name, file, path, desc)
  File "/home/jeff/cbang/config/pkg/__init__.py", line 13, in <module>
    xml_escape_table = str.maketrans({
AttributeError: type object 'str' has no attribute 'maketrans'
Traceback (most recent call last):
  File "/home/jeff/cbang/config/__init__.py", line 201, in CBTryLoadTool
    env.Tool(name, toolpath = [path])
  File "/usr/lib/scons/SCons/Environment.py", line 1788, in Tool
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 118, in __init__
    module = self._tool_module()
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 145, in _tool_module
    mod, file = self._load_dotted_module_py2(self.name, self.name, self.toolpath)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 130, in _load_dotted_module_py2
    mod = imp.load_module(full_name, file, path, desc)
  File "/home/jeff/cbang/config/pkg/__init__.py", line 13, in <module>
    xml_escape_table = str.maketrans({
AttributeError: type object 'str' has no attribute 'maketrans'
Failed to load tool pkg from the following paths:
  ./config
  /home/jeff/cbang/config
  ./config
Have you set PKG_HOME?
Traceback (most recent call last):
  File "/home/jeff/cbang/config/__init__.py", line 201, in CBTryLoadTool
    env.Tool(name, toolpath = [path])
  File "/usr/lib/scons/SCons/Environment.py", line 1789, in Tool
    tool(self)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 298, in __call__
    self.generate(env, *args, **kw)
  File "/home/jeff/cbang/config/packager/__init__.py", line 315, in generate
    env.CBLoadTool(tool)
  File "/usr/lib/scons/SCons/Environment.py", line 224, in __call__
    return self.method(*nargs, **kwargs)
  File "/home/jeff/cbang/config/__init__.py", line 239, in CBLoadTool
    raise Exception('Failed to load tool ' + name)
Exception: Failed to load tool pkg
Failed to load tool packager from the following paths:
  /home/jeff/cbang/config
  ./config
Have you set PACKAGER_HOME?
Exception: Failed to load tool packager:
  File "/home/jeff/cbang/SConstruct", line 28:
    env.CBLoadTools('packager compiler cbang build_info resources')
  File "/usr/lib/scons/SCons/Environment.py", line 224:
    return self.method(*nargs, **kwargs)
  File "/home/jeff/cbang/config/__init__.py", line 244:
    for name in tools: env.CBLoadTool(name, paths)
  File "/usr/lib/scons/SCons/Environment.py", line 224:
    return self.method(*nargs, **kwargs)
  File "/home/jeff/cbang/config/__init__.py", line 239:
    raise Exception('Failed to load tool ' + name)
````

**Comment by Hou5e** [comment]
Trying to install the prerequisites, you get this message error that: libssl-dev wants to delete npm, and npm wants to delete libssl-dev:
```
sudo apt-get install -y scons git npm build-essential libssl-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
npm is already the newest version (3.5.2-0ubuntu4).
scons is already the newest version (3.0.1-1).
git is already the newest version (1:2.17.1-1ubuntu0.13).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: node-gyp (>= 0.10.9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by kbernhagen** [comment]
The cbang scons build system requires python3
I am using python 3.9 and 3.10

**Comment by kbernhagen** [comment]
You only need npm for fah-web-client-bastet

**Comment by Hou5e** [comment]
Switching to the already installed Python v3.6.9, you get a smaller error message:
```
python --version
Python 3.6.9
jeff@X99-15:~$ export CBANG_HOME=$PWD/cbang
jeff@X99-15:~$ scons -C cbang
scons: Entering directory `/home/jeff/cbang'
scons: Reading SConscript files ...
Traceback (most recent call last):
  File "/home/jeff/cbang/config/__init__.py", line 201, in CBTryLoadTool
    env.Tool(name, toolpath = [path])
  File "/usr/lib/scons/SCons/Environment.py", line 1789, in Tool
    tool(self)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 298, in __call__
    self.generate(env, *args, **kw)
  File "/home/jeff/cbang/config/test/__init__.py", line 17, in generate
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'
Traceback (most recent call last):
  File "/home/jeff/cbang/config/__init__.py", line 201, in CBTryLoadTool
    env.Tool(name, toolpath = [path])
  File "/usr/lib/scons/SCons/Environment.py", line 1789, in Tool
    tool(self)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 298, in __call__
    self.generate(env, *args, **kw)
  File "/home/jeff/cbang/config/test/__init__.py", line 17, in generate
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'
Failed to load tool test from the following paths:
  /home/jeff/cbang/config
  ./config
Have you set TEST_HOME?
Exception: Failed to load tool test:
  File "/home/jeff/cbang/SConstruct", line 29:
    conf = env.CBConfigure()
  File "/usr/lib/scons/SCons/Environment.py", line 224:
    return self.method(*nargs, **kwargs)
  File "/home/jeff/cbang/config/__init__.py", line 328:
    env.CBLoadTool('test')
  File "/usr/lib/scons/SCons/Environment.py", line 224:
    return self.method(*nargs, **kwargs)
  File "/home/jeff/cbang/config/__init__.py", line 239:
    raise Exception('Failed to load tool ' + name)
```

**Comment by kbernhagen** [comment]
Did you try venv or virtualenv?
I think some files just say "python", which may be python2 if have it installed.

**Comment by kbernhagen** [comment]
What version of scons do you have?

**Comment by Hou5e** [comment]
I added Python v3.10, from: https://www.itsupportwale.com/blog/how-to-upgrade-to-python-3-10-on-ubuntu-18-04-and-20-04-lts/   and the error message is smaller (and the same error to anything now).
Version: scons is already the newest version (3.0.1-1) from the package manager. I'll look into the scons version next.
```
python3 -V
Python 3.10.9
jeff@X99-15:~$ export CBANG_HOME=$PWD/cbang
jeff@X99-15:~$ scons -C cbang
Traceback (most recent call last):
  File "/usr/bin/scons", line 99, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 943, in <module>
    collections.MutableMapping.register(ParseResults)
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by Hou5e** [comment]
I'm going to punt on this one, Linux looks somewhat broken after a reboot. I'm just going to install a newer Linux on that PC.

**Comment by jcoffland** [comment]
I have a work around for this that will be in v8.1.6

**Comment by Hou5e** [comment]
I was able to install FAH Client v8.1.6 on Mint 19.0. It looks like this issue is resolved. I'm going to close it. Thanks :-)
